### PR TITLE
trycatch

### LINKED ISSUE #31: observableEither.tryCatch
Is there any purpose for this not being in the library for ObservableEither? 

Would you accept a PR?

docs to help: https://rxjs.dev/api/operators/catchError

### PR DESCRIPTION
**Pull request by anthonyjoeseph**
Closes #31

Related: gcanti/fp-ts#1376

Version of https://github.com/gcanti/fp-ts-rxjs/pull/46, branched from 0.6.12

### CODE REVIEW

**Comment by gcanti** [comment]
@anthonyjoeseph what about a simpler signature?

```ts
/**
 * @category constructors
 * @since 0.6.12
 */
export const tryCatch: <A>(a: Observable<A>) => ObservableEither<unknown, A> =
  /*#__PURE__*/
  flow(R.map(E.right), catchError(flow(E.left, R.of)))
```

**Comment by anthonyjoeseph** [comment]
I love that signature! Updated

**Comment by gcanti** [comment]
@anthonyjoeseph thanks. This branch has conflicts, maybe you have an old `docs-ts` version locally.

**Comment by anthonyjoeseph** [comment]
Ah thanks for the tip! I wasn't sure why that kept happening. Updated

**Comment by OliverJAsh** [comment]
It looks like this version of `tryCatch` doesn't accept a function to handle/convert the error, unlike all other implementations of `tryCatch` such as `TaskEither.tryCatch`. Are we planning to make all other implementations match this one, or should we make this one consistent with the rest?

**Comment by gcanti** [comment]
> Are we planning to make all other implementations match this one

yes

**Pull request merged**
