### PR TITLE
ReaderObservable added

### PR DESCRIPTION
**Pull request by mlegenhausen**
This is mainly a port of the `ReaderTask` from `fp-ts`.

I also added `MonadObservable` to provide `fromObservable`.

### CODE REVIEW

**Review by gcanti — APPROVED** [review]

**Comment by mlegenhausen** [comment]
@gcanti any concerns left before merge?

**Comment by gcanti** [comment]
@mlegenhausen no no, feel free to merge (I thought you wanted to add something more so I was waiting)

**Comment by mlegenhausen** [comment]
Done

**Comment by gcanti** [comment]
Thanks @mlegenhausen, going to release v0.6.6 asap

**Comment by gcanti** [comment]
Released

**Comment by mlegenhausen** [comment]
@gcanti thanks!

**Pull request merged**
